# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("linear", "linear_X", "linear_fixed_intercept", "linear_no_p", "splines", "splines_fixed", "splines_interaction", "splines_interaction_fixed", "splines_interaction_sparse")

# load each stan module
Rcpp::loadModule("stan_fit4linear_mod", what = TRUE)
Rcpp::loadModule("stan_fit4linear_X_mod", what = TRUE)
Rcpp::loadModule("stan_fit4linear_fixed_intercept_mod", what = TRUE)
Rcpp::loadModule("stan_fit4linear_no_p_mod", what = TRUE)
Rcpp::loadModule("stan_fit4splines_mod", what = TRUE)
Rcpp::loadModule("stan_fit4splines_fixed_mod", what = TRUE)
Rcpp::loadModule("stan_fit4splines_interaction_mod", what = TRUE)
Rcpp::loadModule("stan_fit4splines_interaction_fixed_mod", what = TRUE)
Rcpp::loadModule("stan_fit4splines_interaction_sparse_mod", what = TRUE)

# instantiate each stanmodel object
stanmodels <- sapply(stanmodels, function(model_name) {
  # create C++ code for stan model
  stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
  stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
  stanfit <- rstan::stanc_builder(stan_file,
                                  allow_undefined = TRUE,
                                  obfuscate_model_name = FALSE)
  stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                            model_cppcode = stanfit$cppcode)
  # create stanmodel object
  methods::new(Class = "stanmodel",
               model_name = stanfit$model_name,
               model_code = stanfit$model_code,
               model_cpp = stanfit$model_cpp,
               mk_cppmodule = function(x) get(paste0("model_", model_name)))
})
